package andres.rangel.currencyconverter.utils

object Constants {
    const val BASE_URL = "https://api.apilayer.com/"
    const val API_KEY = "hzej3dr9GAsvPWRdAR6cVAtAgdMyH4V1"
    val SYMBOLS = mapOf(
        "United Arab Emirates Dirham" to "AED",
        "Afghan Afghani" to "AFN",
        "Albanian Lek" to "ALL",
        "Armenian Dram" to "AMD",
        "Netherlands Antillean Guilder" to "ANG",
        "Angolan Kwanza" to "AOA",
        "Argentine Peso" to "ARS",
        "Australian Dollar" to "AUD",
        "Aruban Florin" to "AWG",
        "Azerbaijani Manat" to "AZN",
        "Bosnia-Herzegovina Convertible Mark" to "BAM",
        "Barbadian Dollar" to "BBD",
        "Bangladeshi Taka" to "BDT",
        "Bulgarian Lev" to "BGN",
        "Bahraini Dinar" to "BHD",
        "Burundian Franc" to "BIF",
        "Bermudan Dollar" to "BMD",
        "Brunei Dollar" to "BND",
        "Bolivian Boliviano" to "BOB",
        "Brazilian Real" to "BRL",
        "Bahamian Dollar" to "BSD",
        "Bitcoin" to "BTC",
        "Bhutanese Ngultrum" to "BTN",
        "Botswanan Pula" to "BWP",
        "New Belarusian Ruble" to "BYN",
        "Belarusian Ruble" to "BYR",
        "Belize Dollar" to "BZD",
        "Canadian Dollar" to "CAD",
        "Congolese Franc" to "CDF",
        "Swiss Franc" to "CHF",
        "Chilean Unit of Account (UF)" to "CLF",
        "Chilean Peso" to "CLP",
        "Chinese Yuan" to "CNY",
        "Colombian Peso" to "COP",
        "Costa Rican Colón" to "CRC",
        "Cuban Convertible Peso" to "CUC",
        "Cuban Peso" to "CUP",
        "Cape Verdean Escudo" to "CVE",
        "Czech Republic Koruna" to "CZK",
        "Djiboutian Franc" to "DJF",
        "Danish Krone" to "DKK",
        "Dominican Peso" to "DOP",
        "Algerian Dinar" to "DZD",
        "Egyptian Pound" to "EGP",
        "Eritrean Nakfa" to "ERN",
        "Ethiopian Birr" to "ETB",
        "Euro" to "EUR",
        "Fijian Dollar" to "FJD",
        "Falkland Islands Pound" to "FKP",
        "British Pound Sterling" to "GBP",
        "Georgian Lari" to "GEL",
        "Guernsey Pound" to "GGP",
        "Ghanaian Cedi" to "GHS",
        "Gibraltar Pound" to "GIP",
        "Gambian Dalasi" to "GMD",
        "Guinean Franc" to "GNF",
        "Guatemalan Quetzal" to "GTQ",
        "Guyanaese Dollar" to "GYD",
        "Hong Kong Dollar" to "HKD",
        "Honduran Lempira" to "HNL",
        "Croatian Kuna" to "HRK",
        "Haitian Gourde" to "HTG",
        "Hungarian Forint" to "HUF",
        "Indonesian Rupiah" to "IDR",
        "Israeli New Sheqel" to "ILS",
        "Manx pound" to "IMP",
        "Indian Rupee" to "INR",
        "Iraqi Dinar" to "IQD",
        "Iranian Rial" to "IRR",
        "Icelandic Króna" to "ISK",
        "Jersey Pound" to "JEP",
        "Jamaican Dollar" to "JMD",
        "Jordanian Dinar" to "JOD",
        "Japanese Yen" to "JPY",
        "Kenyan Shilling" to "KES",
        "Kyrgystani Som" to "KGS",
        "Cambodian Riel" to "KHR",
        "Comorian Franc" to "KMF",
        "North Korean Won" to "KPW",
        "South Korean Won" to "KRW",
        "Kuwaiti Dinar" to "KWD",
        "Cayman Islands Dollar" to "KYD",
        "Kazakhstani Tenge" to "KZT",
        "Laotian Kip" to "LAK",
        "Lebanese Pound" to "LBP",
        "Sri Lankan Rupee" to "LKR",
        "Liberian Dollar" to "LRD",
        "Lesotho Loti" to "LSL",
        "Lithuanian Litas" to "LTL",
        "Latvian Lats" to "LVL",
        "Libyan Dinar" to "LYD",
        "Moroccan Dirham" to "MAD",
        "Moldovan Leu" to "MDL",
        "Malagasy Ariary" to "MGA",
        "Macedonian Denar" to "MKD",
        "Myanma Kyat" to "MMK",
        "Mongolian Tugrik" to "MNT",
        "Macanese Pataca" to "MOP",
        "Mauritanian Ouguiya" to "MRO",
        "Mauritian Rupee" to "MUR",
        "Maldivian Rufiyaa" to "MVR",
        "Malawian Kwacha" to "MWK",
        "Mexican Peso" to "MXN",
        "Malaysian Ringgit" to "MYR",
        "Mozambican Metical" to "MZN",
        "Namibian Dollar" to "NAD",
        "Nigerian Naira" to "NGN",
        "Nicaraguan Córdoba" to "NIO",
        "Norwegian Krone" to "NOK",
        "Nepalese Rupee" to "NPR",
        "New Zealand Dollar" to "NZD",
        "Omani Rial" to "OMR",
        "Panamanian Balboa" to "PAB",
        "Peruvian Nuevo Sol" to "PEN",
        "Papua New Guinean Kina" to "PGK",
        "Philippine Peso" to "PHP",
        "Pakistani Rupee" to "PKR",
        "Polish Zloty" to "PLN",
        "Paraguayan Guarani" to "PYG",
        "Qatari Rial" to "QAR",
        "Romanian Leu" to "RON",
        "Serbian Dinar" to "RSD",
        "Russian Ruble" to "RUB",
        "Rwandan Franc" to "RWF",
        "Saudi Riyal" to "SAR",
        "Solomon Islands Dollar" to "SBD",
        "Seychellois Rupee" to "SCR",
        "Sudanese Pound" to "SDG",
        "Swedish Krona" to "SEK",
        "Singapore Dollar" to "SGD",
        "Saint Helena Pound" to "SHP",
        "Sierra Leonean Leone" to "SLL",
        "Somali Shilling" to "SOS",
        "Surinamese Dollar" to "SRD",
        "São Tomé and Príncipe Dobra" to "STD",
        "Salvadoran Colón" to "SVC",
        "Syrian Pound" to "SYP",
        "Swazi Lilangeni" to "SZL",
        "Thai Baht" to "THB",
        "Tajikistani Somoni" to "TJS",
        "Turkmenistani Manat" to "TMT",
        "Tunisian Dinar" to "TND",
        "Tongan Paʻanga" to "TOP",
        "Turkish Lira" to "TRY",
        "Trinidad and Tobago Dollar" to "TTD",
        "New Taiwan Dollar" to "TWD",
        "Tanzanian Shilling" to "TZS",
        "Ukrainian Hryvnia" to "UAH",
        "Ugandan Shilling" to "UGX",
        "United States Dollar" to "USD",
        "Uruguayan Peso" to "UYU",
        "Uzbekistan Som" to "UZS",
        "Venezuelan Bolívar Fuerte" to "VEF",
        "Vietnamese Dong" to "VND",
        "Vanuatu Vatu" to "VUV",
        "Samoan Tala" to "WST",
        "CFA Franc BEAC" to "XAF",
        "Silver (troy ounce)" to "XAG",
        "Gold (troy ounce)" to "XAU",
        "East Caribbean Dollar" to "XCD",
        "Special Drawing Rights" to "XDR",
        "CFA Franc BCEAO" to "XOF",
        "CFP Franc" to "XPF",
        "Yemeni Rial" to "YER",
        "South African Rand" to "ZAR",
        "Zambian Kwacha (pre-2013)" to "ZMK",
        "Zambian Kwacha" to "ZMW",
        "Zimbabwean Dollar" to "ZWL"
    )
}